import Head from "next/head";
import EventList from "../components/EventList";
import { getFeaturedEvents } from "../helpers/api-utils";

export default function Home({ featuredEvent }) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <EventList items={featuredEvent} />
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const events = await getFeaturedEvents();

  return {
    props: {
      featuredEvent: events,
    },
    revalidate : 1800
  };
};
