import Head from "next/head";
import EventList from "../components/EventList";
import { getFeaturedEvents } from "../dummy-data";

export default function Home({ featuredEvent }) {
  const featuredEvents = getFeaturedEvents(featuredEvent);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <EventList items={featuredEvents} />
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const response = await fetch(
    "https://sales-c4869-default-rtdb.firebaseio.com/events.json"
  );

  const data = await response.json();

  const transformedData = [];

  for (let key in data) {
    transformedData.push({
      id: key,
      title: data[key].title,
      description: data[key].description,
      location: data[key].title,
      date: data[key].date,
      image: data[key].image,
      isFeatured: data[key].isFeatured,
    });
  }

  return {
    props: {
      featuredEvent: transformedData,
    },
  };
};
